@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzcyMzk2ZjEwMmM1MGFkZDYxYWM0NjMiLCJmdWxsbmFtZSI6IlNhaHJmZWFyIE1hY2FydGh5IiwiZW1haWwiOiJzYWhyZmVhckBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MzczNTQ4NzN9.76giBIC5Dn6EqXmWaebUHJ6ETnrEaBR2u6Gcq_cPHIA


# Sign In to Get the Token
POST http://localhost:4007/users/signin
Content-Type: application/json

{
    "email": "sahrfear@gmail.com",
    "password": "sahrfear"
}

###
GET  http://localhost:4007/property
Authorization:Bearer {{authToken}}


### PATCH Request to Update Property Status
PATCH http://localhost:4007/property/678df398d682e056ac2d2416
Content-Type: application/json
Authorization: Bearer {{authToken}}


{
    "status": "approved"
}


