@FILENAME1 =assets/estate.jpg
@FILENAME2 =assets/estate2.jpg
@FILENAME3 =assets/estate3.jpg

@FILE_FORM_NAME=estatefile
@FILENAME =assets/estate3.jpg
@FILE_MIME_TYPE=image/jpeg

@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzczMzcwNzc1NDc2ZTg1Y2UyNjcyYmUiLCJmdWxsbmFtZSI6Ik1hbWllc2lhIE1hY2FydGh5IiwiZW1haWwiOiJtYW1pZXNpYUBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTczNTc2NjA3MH0.SR4JeGIvTLTDoCglHdprFdK3BYTVE-JovLvUsaRj34A
@mamiesiaToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzczMzcwNzc1NDc2ZTg1Y2UyNjcyYmUiLCJmdWxsbmFtZSI6Ik1hbWllc2lhIE1hY2FydGh5IiwiZW1haWwiOiJtYW1pZXNpYUBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTczNjg2NDc4N30.eaaC3jhm1UnGFPFP1piHIHN40BOG3OhMCX05HYf51II
@maryanneToken =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzcyMzk5ZDEwMmM1MGFkZDYxYWM0NjciLCJmdWxsbmFtZSI6Ik1hcnlhbm5lIEJpbWUiLCJlbWFpbCI6Im1hcnlhbm5lQGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzM2ODY0ODQ4fQ.x3nh64nYVQMiv4k6WYvTaZxMJoSLnp2kWJj4Lxj1rNY
@sahrfearToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzcyMzk2ZjEwMmM1MGFkZDYxYWM0NjMiLCJmdWxsbmFtZSI6IlNhaHJmZWFyIE1hY2FydGh5IiwiZW1haWwiOiJzYWhyZmVhckBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MzY4NjQ4MTh9.Q1Bg-OtCu4X_9WYaNowfczQ2fGE2vx7H7l4e5FXhWO0

# Sign In to Get the Token
POST http://localhost:4007/users/signin
Content-Type: application/json

{
    "email": "mamiesia@gmail.com",
    "password": "mamiesia"
}

###
POST http://localhost:4007/users/signin
Content-Type: application/json

{
    "email": "sahrfear@gmail.com",
    "password": "sahrfear"
}

###
POST http://localhost:4007/users/signin
Content-Type: application/json

{
    "email": "maryanne@gmail.com",
    "password": "maryanne"
}
###

# Add a New Property
POST http://localhost:4007/property/add
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer {{maryanneToken}}

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"

Fancy Villa
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="description"

Million dollar view of the city that you can't resist very fancy Added By Maryanne
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="location[address]"

1234 New Tech Drive
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="location[city]"

San Franscisco
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="location[state]"

USA
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="location[postalCode]"

95112
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="location[coordinates][lat]"

47.3382
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="location[coordinates][lng]"

-121.8863
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="price"

6000
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="propertyType"

apartment
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="listingType"

rent
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="status"

pending
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="features[bedrooms]"

4
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="features[bathrooms]"

10
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="features[area]"

1899
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="{{FILE_FORM_NAME}}"; filename="estate.jpg"
Content-Type: image/jpeg

< ./assets/estate.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="{{FILE_FORM_NAME}}"; filename="estate2.jpg"
Content-Type: image/jpeg

< ./assets/estate2.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="{{FILE_FORM_NAME}}"; filename="estate3.jpg"
Content-Type: image/jpeg

< ./assets/estate3.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

# Get apartment by id
###
GET  http://localhost:4007/property/676d9899fe19125be10cdc3c
Authorization:Bearer {{authToken}}


# Update Property by id
###
PUT http://localhost:4007/property/676d9dc406490ed7c46a4883
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer {{authToken}}

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"

Fancy Apartment
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="description"

Million dollar view of the city that you can't resist.
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="location[address]"

5678 New Tech Drive
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="location[city]"

Koidu
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="location[state]"

KD
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="price"

4000
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="features[bedrooms]"

1
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="estatefile"; filename="estate2.jpg"
Content-Type: image/jpeg

< ./estate2.jpg>
------WebKitFormBoundary7MA4YWxkTrZu0gW--

# Patch Property by id: it partially updates the property
##
PATCH http://localhost:4007/property/67645b0e8681e3f610937400
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer {{authToken}}

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="listingType"

rent
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="propertyType"

townhouse
------WebKitFormBoundary7MA4YWxkTrZu0gW--

# Delete Property by id and owner id
###
DELETE http://localhost:4007/property/675b313592a59886d2797b3f
Authorization: Bearer {{authToken}}



# Get all proptety type
###
GET  http://localhost:4007/property/type/house
Authorization:Bearer {{authToken}}

# Get property by listing type
###
GET  http://localhost:4007/property/listing/type/rent
Authorization:Bearer {{authToken}}


# Add Review
###
POST http://localhost:4007/property/677242f698fc9bc0d6d6d110/reviews
Content-Type: application/json
Authorization: Bearer {{mamiesiaToken}}

{
    "review": "This review is added by Mamie Sia. The owner is Sahrfear",
    "rating": 5
}
###
POST http://localhost:4007/property/677242f698fc9bc0d6d6d110/reviews
Content-Type: application/json
Authorization: Bearer {{maryanneToken}}

{
    "review": "This review is added by Maryanne. The owner is Sahrfear",
    "rating": 2
}


# Get all reviews
###
GET  http://localhost:4007/property/677242b73629b2ba76727b6f/reviews

# Get review by id
###
GET  http://localhost:4007/property/677242b73629b2ba76727b6f/reviews/6774db76a7c617e697d30e85

# Delete Review by review id
###
DELETE http://localhost:4007/property/6775b2caa4fa810b21151a4b/reviews/6775b98a7f2e6788fec4265c
Authorization: Bearer {{sahrfearToken}}

# Update Review by review id
###
PUT http://localhost:4007/property/677242f698fc9bc0d6d6d110/reviews/678677805c3f819cd3b60b2f
Content-Type: application/json
Authorization: Bearer {{mamiesiaToken}}

{
    "review": "This review is updated by MamieSia. The owner is sahrfear",
    "rating": 1
}