# @name login
# Sign Up
POST http://localhost:4007/users/signup
Content-Type: application/json

{
    "fullname": "Maryanne Bime",
     "email": "maryanne@gmail.com",
    "password": "maryanne"
}

# Sign In
###
POST http://localhost:4007/users/signin
Content-Type: application/json

{
    "email": "sahrfear@gmail.com",
    "password": "sahrfear"
}

###
# Post a profile Picture assets/myProfile.jpeg
@FILENAME =assets/myProfile.jpg
@FILE_FORM_NAME=userfile
# @FILE_MIME_TYPE=assets/jpg
@FILE_MIME_TYPE=image/jpeg
@user_id =676d9786fe19125be10cdc31

@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzZkOTc4NmZlMTkxMjViZTEwY2RjMzEiLCJmdWxsbmFtZSI6IlNpYSBNYWNhcnRoeSIsImVtYWlsIjoic2lhQGdtYWlsLmNvbSIsImlhdCI6MTczNTIzNTQ3MX0.-fJ38fbwVIkucNeGiZBY7t1oq__54hVx2--eqeRQ4W4


###
POST http://localhost:4007/users/{{user_id}}/add_profile
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer {{authToken}}

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="{{FILE_FORM_NAME}}"; filename="{{FILENAME}}"
Content-Type: {{FILE_MIME_TYPE}}


< ./{{FILENAME}}
------WebKitFormBoundary7MA4YWxkTrZu0gW--



###
#Remove profile picture
DELETE http://localhost:4007/users/{{user_id}}/remove_profile
Authorization: Bearer {{authToken}}