# @name login
# Sign Up
POST http://localhost:4007/users/signup
Content-Type: application/json

{
    "fullname": "Sia Tia",
    "email": "sia@gmail.com",
    "password": "sia"
}

# Sign In
###
POST http://localhost:4007/users/signin
Content-Type: application/json

{
     "email": "sia@gmail.com",
    "password": "sia"
}

###
# Post a profile Picture assets/myProfile.jpeg
@FILENAME =assets/estate.jpg
@FILE_FORM_NAME=userfile
@FILE_MIME_TYPE=assets/jpg
# @FILE_MIME_TYPE=image/jpeg
@user_id =675624da81be76edfaa59847

@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzU2NGMxMWUwZDE1MjdkZTBhNTVmZTUiLCJmdWxsbmFtZSI6IlNpYSBUaWEiLCJlbWFpbCI6InNpYUBnbWFpbC5jb20iLCJpYXQiOjE3MzM3MDg4NDJ9.NTq07Jr-e5kjOIYpR48lwkMYbQJ5S_jEBRpt8nL4mZQ


###
POST http://localhost:4007/users/{{user_id}}/add_profile
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer {{authToken}}

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="{{FILE_FORM_NAME}}"; filename="{{FILENAME}}"
Content-Type: {{FILE_MIME_TYPE}}


< ./{{FILENAME}}
------WebKitFormBoundary7MA4YWxkTrZu0gW--



###
#Remove profile picture
DELETE http://localhost:4007/users/{{user_id}}/remove_profile
Authorization: Bearer {{authToken}}