### Login to make payment
@tiaToken =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzhkZWJhYmM5MWI2MDUxZjNkMDk1N2EiLCJmdWxsbmFtZSI6IlNpYSBUaWEgTWNDYXJ0aHkiLCJlbWFpbCI6InNpYXRpYUBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTczNzM1NzA3MX0.nCzPJ8jUx-y6NcVcbH3RmrPJ2cKpeOnG9cliyisFK6A
@maryanneToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzcyMzk5ZDEwMmM1MGFkZDYxYWM0NjciLCJmdWxsbmFtZSI6Ik1hcnlhbm5lIEJpbWUiLCJlbWFpbCI6Im1hcnlhbm5lQGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzM3MzU3MTM5fQ.VtYU2T6qLCMUmjhiIsYF9hX8eBzxku4yn3y8ehADMrg
POST http://localhost:4007/users/signin
Content-Type: application/json

{
    "email": "siatia@gmail.com",
    "password": "siatia"
}
###
POST http://localhost:4007/users/signin
Content-Type: application/json

{
    "email": "maryanne@gmail.com",
    "password": "maryanne"
}


### Create Payment
POST http://localhost:4007/property/678df398d682e056ac2d2416/payment 
Content-Type: application/json
Authorization: Bearer {{tiaToken}}

{
  "amount": 1000,
  "currency": "usd",
  "propertyId":"678df398d682e056ac2d2416",
  "userId":"678debabc91b6051f3d0957a"
}

###
POST http://localhost:4007/property/678df15fd682e056ac2d23f3/payment 
Content-Type: application/json
Authorization: Bearer {{maryanneToken}}

{
  "amount": 7000,
  "currency": "usd",
  "propertyId":"678df15fd682e056ac2d23f3",
  "userId":"6772399d102c50add61ac467"
}

### Get the payment details
GET http://localhost:4007/property/678df15fd682e056ac2d23f3/payment/678df9330205ee99b8fde371
Authorization: Bearer {{maryanneToken}}


